### ISSUE TITLE
Unable to resolve module `prop-types`

### ISSUE THREAD

**Issue by Joeyrodrigues92** [spencercarli/getting-started-react-native-navigation#1]
![screen shot 2017-12-04 at 9 56 29 am](https://user-images.githubusercontent.com/21230272/33559003-749f96a0-d8d9-11e7-936b-4b4b138e5559.png)

This is the error message im getting. All i did was copy the git hub, npm install. I run mpm start and react0native run-ios, and i get that error message. Its successfully built in xcode but still the error message makes its way onto my simulator. Any help would be awesome thanks.

**Comment by spencercarli** [comment]
You'll wanto install prop-types `npm install --save prop-types` and then migrate any `import React, { PropTypes } from 'react';` to 
```
import React from 'react';
import PropTypes from 'prop-types';
```

Would accept a PR for this so the repo is fixed

**Comment by Joeyrodrigues92** [comment]
Yea man thanks, all i had to do was just run the npm install. Up and running. Thank again

**Comment by spencercarli** [comment]
Glad it worked!
